server:
  port: 9001
spring:
  application:
    name: lanrenspace.edu.hystrix.turbine

#注册到Eureka服务中心
edu:
  eureka: 175.24.45.125
eureka:
  client:
    service-url:
      #defaultZone: http://${edu.eureka}:8761/eureka,http://${edu.eureka}:8762/eureka,http://${edu.eureka}:8763/eureka
      defaultZone: http://${edu.eureka}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

# turbine配置
turbine:
  app-config: lanrenspace.edu.service.autodeliver,lanrenspace.edu.service.resume
  cluster-name-expression: "'default'"